title: Material Components for iOS
description: > # this means to ignore newlines
  Material Components for iOS is a set of user interface components that help iOS app developers build Material Design apps.
basepath: "" # blank if hosted at site root, /subdirectory if hosted in "subdirectory" folder
# temporarily disabled
# url: "http://www.materialcomponents.org"
url: ""
permalink: :title
analytics_id: "UA-51798601-9"


# Build settings
markdown: kramdown

# Kramdown settings
kramdown:
  # Don't use a highlighter.
  # This will output raw code blocks that can be
  # highlighted in javascript with CodeMirror.
  syntax_highlighter: none
  auto_ids: true

#kramdown:
#  #parse_block_html: true
#  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    tab_width: 4
#    line_numbers: true
#    css: style

# Build target
exclude: [build.sh]

defaults:
#layout specification
- scope:
    path: ''
  values:
    layout: detail
# - scope:
#     path: index
#   value:
#     layout: homepage
# - scope:
#     path: howto/index
#   values:
#     layout: landing
# - scope:
#     path: components/index
#   values:
#     layout: landing
#category specification
- scope:
    path: howto
  values:
    categories: howto
- scope:
    path: components
  values:
    categories: components
- scope:
    path: contributing
  values:
    categories: contributing
